### PR TITLE
Email functionality implemented, html needs looking at though

### PR DESCRIPTION
**Pull request by HulaTime**

### CODE REVIEW

**Comment by HulaTime** [comment]
💯

**Comment by festinalent3** [comment]
:shipit:

**Comment by HulaTime** [comment]
🎅

**Comment by HulaTime** [comment]
💃 🐟 🎣 👯 🐶 🐱 🅰️ 🅱️ 🌵 🍼 ✋ 🐫 💨 ❓ 📦 🌴 🍰 🎲 👻 💎 ✌️

**Pull request merged**
